

group "cloud.wondrify"

apply plugin: 'groovy'
apply plugin: 'java-library'
apply plugin: "org.apache.grails.gradle.grails-plugin"

ext {
  grailsVersion = project.grailsVersion
  pomDescription = 'Karman Storage Provider Asset Serving Plugin for Grails'
}


configurations {
  provided
}

dependencies {
  compileOnly 'org.springframework.boot:spring-boot-starter-logging'
  compileOnly "org.springframework.boot:spring-boot-starter-actuator"
  compileOnly "org.springframework.boot:spring-boot-autoconfigure"
  compileOnly "org.springframework.boot:spring-boot-starter-tomcat"
  compileOnly "org.apache.grails:grails-core"
  compileOnly "org.apache.grails:grails-web-boot"
  compileOnly "org.apache.grails:grails-services"
  compileOnly "org.apache.grails:grails-url-mappings"
  runtimeOnly 'javax.servlet:javax.servlet-api:3.1.0'
  testImplementation "org.spockframework:spock-core"
  testImplementation "org.apache.grails:grails-testing-support-web"
  api project(':karman-core')
}
bootJar.enabled = false



apply {
  from rootProject.layout.projectDirectory.file('gradle/java-config.gradle')
  from rootProject.layout.projectDirectory.file('gradle/publish-config.gradle')
}
