apply plugin: 'groovy'
apply plugin: 'java-library'

group = 'cloud.wondrify'

ext {
    pomDescription = 'Karman Storage Provider interface for Azure Cloud Storage api'
}

configurations {
    provided
}
sourceSets {
    main {
        compileClasspath += configurations.provided
    }
}

dependencies {
    implementation "org.apache.groovy:groovy-all:$groovyVersion"

    api project(':karman-core')
    testImplementation 'org.spockframework:spock-core:2.3-groovy-4.0'


    api 'org.apache.httpcomponents:httpcore:4.4.16'
    api 'org.apache.httpcomponents:httpclient:4.5.14'
    api 'commons-beanutils:commons-beanutils:1.9.4'
}


task(console, dependsOn: 'classes', type: JavaExec) {
  main = 'groovy.ui.Console'
  classpath = sourceSets.main.runtimeClasspath
}

test {
    systemProperties System.properties
    testLogging {
        exceptionFormat = 'full'
        showStandardStreams = true
        events 'started', 'passed'
    }
}
apply {
    from rootProject.layout.projectDirectory.file('gradle/java-config.gradle')
    from rootProject.layout.projectDirectory.file('gradle/publish-config.gradle')
}