group = 'cloud.wondrify'

allprojects {
	repositories {
		// mavenLocal()
		mavenCentral()
		maven { url = 'https://repo.grails.org/grails/core' }
		maven {
			url = 'https://repository.apache.org/content/groups/snapshots'
			content {
				includeVersionByRegex('org[.]apache[.]grails.*', '.*', '.*SNAPSHOT')
			}
		}
	}
}

ext {
	publishedProjects = []
    isBuildSnapshot = version.endsWith('-SNAPSHOT')
    isReleaseVersion = !isBuildSnapshot
}

group = 'cloud.wondrify'


if (isReleaseVersion) {
    apply plugin: "io.github.gradle-nexus.publish-plugin"
    nexusPublishing {
        repositories {
            sonatype {
								nexusUrl.set(uri("https://ossrh-staging-api.central.sonatype.com/service/local/"))
                if(project.hasProperty('mavenUser')) {
                    username = mavenDavydotcomUser
                    password = mavenDavydotcomPassword
                }   
            }
        }
    }
} else {
	
    publishing {
        repositories {
            maven {
                url = "http://nexus.bertramlabs.com/content/repositories/snapshots"
                if(project.hasProperty('labsNexusUser')) {
                    credentials {
                        username = labsNexusUser
                        password = labsNexusPassword
                    }
                }
            }
        }
    }
}

subprojects { project ->
	if (project.name != 'karman-docs') {
		publishedProjects << project.name
		apply plugin: 'java'
		apply plugin: 'org.apache.grails.gradle.grails-publish'
	}
}
