apply plugin: 'groovy'
apply plugin: 'java-library'

group = 'cloud.wondrify'

ext {
    pomDescription = 'Karman is a standardized Cloud File Management Interface for Groovy. It provides a unified means and simple DSL for accessing files on the cloud via extensible StorageProviders'
}

configurations {
    provided
    doc.extendsFrom(runtime)
}

dependencies {
    doc "org.apache.groovy:groovy:$groovyVersion"
    doc "org.apache.groovy:groovy-ant:$groovyVersion"
    doc "org.apache.groovy:groovy-templates:$groovyVersion"
    doc "com.github.javaparser:javaparser-core:$javaparserVersion"

    compileOnly "org.apache.groovy:groovy:$groovyVersion"
    compileOnly "org.apache.groovy:groovy-all:$groovyVersion"
    api("commons-logging:commons-logging:1.1.1")
    testImplementation 'org.spockframework:spock-core:2.3-groovy-4.0'
}


groovydoc {
    source = 'src/main/groovy'
    footer = "Karman-Core is Licensed under the APACHE 2 License"
}



task(console, dependsOn: 'classes', type: JavaExec) {
  main = 'groovy.ui.Console'
  classpath = sourceSets.main.runtimeClasspath
}

test {
    testLogging {
        exceptionFormat = 'full'
        showStandardStreams = true
    }
}
tasks.named('groovydoc', Groovydoc).configure { Groovydoc it ->
    it.docTitle "Asset Pipeline Core"
    it.windowTitle "Asset Pipeline For the JVM API Doc"
    it.groovyClasspath = configurations.doc
    it.classpath = configurations.runtime
    // Links to external Javadoc, currently only the J2SE links are working properly
    it.link('http://download.oracle.com/javase/8/docs/api/', 'java.', 'org.xml', 'javax.', 'org.xml.')
    it.link('http://groovy.codehaus.org/api/', 'groovy.', 'org.apache.groovy.')
}

apply {
    from rootProject.layout.projectDirectory.file('gradle/java-config.gradle')
    from rootProject.layout.projectDirectory.file('gradle/publish-config.gradle')
}
