apply plugin: 'groovy'
apply plugin: 'java-library'

group = 'cloud.wondrify'

ext {
	pomDescription = 'Karman Storage Provider interface for CIFS (Samba) File Shares'
}

configurations {
	provided
}
sourceSets {
	main {
		compileClasspath += configurations.provided
	}
}

dependencies {
	implementation "org.apache.groovy:groovy-all:$groovyVersion"
	api project(':karman-core')
	testImplementation 'org.spockframework:spock-core:2.3-groovy-4.0'


	api "eu.agno3.jcifs:jcifs-ng:2.1.7"
	// compile 'jcifs:jcifs:1.3.17'
	api group:'commons-beanutils', name:'commons-beanutils', version:'1.9.3'
}




task(console, dependsOn: 'classes', type: JavaExec) {
	main = 'groovy.ui.Console'
	classpath = sourceSets.main.runtimeClasspath
}

test {
	systemProperties System.properties
	testLogging {
		exceptionFormat = 'full'
		showStandardStreams = true
	}
}

apply {
	from rootProject.layout.projectDirectory.file('gradle/java-config.gradle')
	from rootProject.layout.projectDirectory.file('gradle/publish-config.gradle')
}